# .github/workflows/cypress.yml

name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        
      - name: Install cypress
        run: npm install cypress

      - name: Verify Cypress cache
        run: npx cypress verify

      - name: Run Cypress tests (headless in Chrome)
        run: npx cypress run --browser chrome
