name: Run Cypress Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Clean install
        run: npm ci

      - name: Verify Cypress install
        run: npx cypress verify

      - name: Run Cypress tests
        run: npx cypress run
